import { roleType, User } from "@/repositories/types"

// id:number,
//     email: string,
//     name: string,
//     description: string,
//     role: roleType,
export const dummyUsers:User[] = [
    {
        id:0,
        email: "test@test.com",
        name: "john",
        description: "",
        role: roleType.NORMAL,
    },
    {
        id:1,
        email: "test2@test.com",
        name: "Jason",
        description: "",
        role: roleType.NORMAL,
    },
    {
        id:2,
        email: "test3@test.com",
        name: "Alice",
        description: "",
        role: roleType.NORMAL,
    },
    {
        id:3,
        email: "tes4@test.com",
        name: "Michael",
        description: "",
        role: roleType.NORMAL,
    },
]


export const dummyPosts = [
    {
        id: 0,
        title:"this is first",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1]],
        maxCount: 10,
        status: true,
    },

    {
        id: 1,
        title:"this is 2",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 2,
        title:"this is 3",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 3,
        title:"this is 4",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[3],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 4,
        title:"this is 5",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 5,
        title:"this is 6",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [],
        maxCount: 10,
        status: true,
    },
    {
        id: 6,
        title:"this is 7",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [],
        maxCount: 10,
        status: true,
    },
    {
        id: 7,
        title:"this is 8",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 8,
        title:"this is 9",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
    {
        id: 9,
        title:"this is 10",
        desc: "submtitlel fieksl get some fkslsfjellies,ejfsk  dfsl",
        createdAt: "2022-12-22",
        deadlineAt: "2024-12-23",
        members: [dummyUsers[0],dummyUsers[1],dummyUsers[2]],
        maxCount: 10,
        status: true,
    },
]